### ISSUE TITLE
Add FAQ for Event

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#652]
**Is it a ?**

**Feature Request**
    
**Description**

The API suports FAQ for event. This issue is aimed at implementing all the features of an FAQ listed [here](https://open-event-api.herokuapp.com/#faq)

- [x] FAQ List #667 
- [x] Create FAQ #677 
- [x] Delete FAQ #728 

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
Solved by #554

**Comment by Masquerade0097** [comment]
@iamareebjamal This issue is for implementing all the features of FAQ that the API supports ie Create, List, Update and Delete operations. Till now only List feature is implemented. So this issue is still unsolved.

**Comment by iamareebjamal** [comment]
@Masquerade0097 Status?

**Comment by Masquerade0097** [comment]
@iamareebjamal Sorry to reply late, didn't see it earlier. Please specify UI details regarding the option to edit or delete.

**Comment by iamareebjamal** [comment]
What do you have in mind?

**Comment by Masquerade0097** [comment]
I think there should be a longClickListener for each item in the list such that on long pressing the item, it get selected and the toolbar shows the option to edit or delete it.
Or Toolbar shows the delete button on clicking which delete button for each item get visible.

**Comment by iamareebjamal** [comment]
Should this be closed?

**Comment by Masquerade0097** [comment]
Ya, I'm closing it.
